packages:  
  - "apps/*"  
  - "packages/*"  
  - "tooling/*"  
  
catalog:  
  prettier: ^3.0.0  
  eslint: ^9.0.0  
  typescript: ^5.8.3  
  tailwindcss: ^3.4.0  
  zod: ^3.23.0  
  "@trpc/server": ^11.0.0  
  "@tanstack/react-query": ^5.0.0  
  "@trpc/client": ^11.0.0  
  "@trpc/tanstack-react-query": ^11.0.0  
  react19: ^19.0.0  
  
catalogs:  
  react19:  
    react: 19.0.0  
    react-dom: 19.0.0  
    "@types/react": ^19.0.0  
    "@types/react-dom": ^19.0.0